# Generated by Django 5.1.5 on 2025-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_checkin_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
