# Generated by Django 5.1.5 on 2025-02-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0004_customuser_lastname_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
